accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.register, name="signup"),
    path('<int:pk>/profile', views.ShowProfilePageView.as_view(), name="profile"),
]

goodreads/urls.py
from django.contrib import admin
from django.urls import re_path,path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name="home"),
    path('index/', views.TestPage.as_view(), name="test"),
    path('search/', views.SearchPage.as_view(), name='search'),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('livros/',include("livros.urls", namespace="livros")),
    path('resenhas/', include('resenhas.urls', namespace='resenhas')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

livros/urls.py
from django.conf.urls import url
from django.urls import re_path, include, path
from . import views

app_name = 'livros'
urlpatterns = [
    re_path(r'search/$', views.ProcuraLivro.as_view(), name='search'),
    url(r'^all/', views.ListaLivro.as_view(), name='all'),
    url(r'^new/$', views.CriaLivro.as_view(), name='create'),
    url(r'in/(?P<pk>[-\w]+)/$', views.UmLivro.as_view(), name='single'),
    path('join/<int:pk>', views.IncluiLivroNaLista.as_view(), name='join'),
    path('leave/<int:pk>/', views.RetiraLivroDaLista.as_view(), name='leave'),
    #re_path('<int:pk>/resenhas',include("resenhas.urls", namespace="resenhas")),
]

resenhas/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'resenhas'

urlpatterns = [
    path('<int:pk>/', views.adiciona_resenha, name='adiciona_resenha'),
    path('<int:pk>/aprova/', views.aprova_resenha, name='aprova_resenha'),
    path('<int:pk>/remove/', views.remove_resenha, name='remove_resenha'),
]

livros/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django import template
from django.db import models
from django.urls import reverse
from autor.models import Autor
from genero.models import Genero
from editora.models import Editora

# Create your models here.
User = get_user_model()
register = template.Library()

class Livro(models.Model):
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE,  default='')
    editora = models.ForeignKey(Editora, on_delete=models.CASCADE,  default='')
    genero = models.ForeignKey(Genero, on_delete=models.CASCADE,  default='')
    titulo = models.CharField(max_length=50, unique=True)
    nota_media = models.DecimalField(blank=True, max_digits=3, decimal_places=1)
    num_paginas = models.IntegerField()
    data_publicacao = models.DateField()
    total_de_notas = models.IntegerField()
    capa = models.ImageField(upload_to='livros/capas/',blank=True, default='', null=True)
    leitores = models.ManyToManyField(User,through="UsuarioLivro")

    def __str__(self):
        return self.titulo

    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('livros:single',kwargs={'pk':self.pk})

    class Meta:
        ordering = ['titulo']


class UsuarioLivro(models.Model):
    livro_id   = models.ForeignKey(Livro,related_name='leitor', on_delete=models.CASCADE)
    usuario_id = models.ForeignKey(User, related_name='livro_usuario', on_delete=models.CASCADE)

    def __str__(self):
        return self.usuario_id.username

    class Meta:
        unique_together = ('livro_id','usuario_id')

livros/views.py
from django.shortcuts import render
from django.contrib import messages
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404

from livros.models import Livro, UsuarioLivro
from accounts.views import superuser_required

from django.db import connection

# Create your views here.
class CriaLivro(LoginRequiredMixin,generic.CreateView):
    print(connection.queries)
    fields = ('titulo', 'num_paginas', 'data_publicacao', 'total_de_notas',
            'nota_media', 'autor', 'editora', 'genero', 'capa')
    model = Livro

    redirect_field_name = 'livros/livro_detail.html'

class UmLivro(generic.DetailView):
    model = Livro
    def get_object(self, queryset=None):
        # Use a custom queryset if provided; this is required for subclasses
        # like DateDetailView
        if queryset is None:
            queryset = self.get_queryset()
        # Next, try looking up by primary key.
        pk = self.kwargs.get(self.pk_url_kwarg)
        slug = self.kwargs.get(self.slug_url_kwarg)
        if pk is not None:
            queryset = queryset.filter(pk=pk)
            print(queryset.query)
        # Next, try looking up by slug.
        if slug is not None and (pk is None or self.query_pk_and_slug):
            slug_field = self.get_slug_field()
            queryset = queryset.filter(**{slug_field: slug})
        # If none of those are defined, it's an error.
        if pk is None and slug is None:
            raise AttributeError(
                "Generic detail view %s must be called with either an object "
                "pk or a slug in the URLconf." % self.__class__.__name__
            )
        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(_("No %(verbose_name)s found matching the query") %
                          {'verbose_name': queryset.model._meta.verbose_name})
        return obj

class ListaLivro(generic.ListView):
    model = Livro
    def get_queryset(self):
        object_list = self.model.objects.all()
        print(object_list.query)

        return object_list

class IncluiLivroNaLista(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args,**kwargs):
        return reverse('livros:single',kwargs={'pk':self.kwargs.get('pk')})

    def get(self,request,*args,**kwargs):
        livro = get_object_or_404(Livro, pk=self.kwargs.get('pk'))

        try:
            UsuarioLivro.objects.create(usuario_id=self.request.user, livro_id=livro)
        except IntegrityError:
            messages.warning(self.request,'Você já tem o livro na lista')
        else:
            messages.success(self.request,'O livro foi incluido na sua lista!')

        return super().get(request,*args,**kwargs)

class RetiraLivroDaLista(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args,**kwargs):
        return reverse('livros:single',kwargs={'pk':self.kwargs.get('pk')})

    def get(self,request,*args,**kwargs):

        try:
            leitor = UsuarioLivro.objects.filter(
                usuario_id=self.request.user,
                livro_id__pk=self.kwargs.get('pk')
            ).get()
        except UsuarioLivro.DoesNotExist:
            messages.warning(self.request,'Desculpa, esse livro não se encontra em sua lista!')
        else:
            leitor.delete()
            messages.success(self.request, 'O livro saiu da sua lista')

        return super().get(request,*args,**kwargs)

class ProcuraLivro(generic.ListView):
    model = Livro
    def get_queryset(self):
        query = self.request.GET.get('q')
        select_atribute =  self.request.GET.get('select_atribute')
        if query:
            if select_atribute == 'titulo':
                object_list = self.model.objects.filter(titulo__icontains=query)
                print(object_list.query)
            elif select_atribute == 'autor':
                object_list = self.model.objects.filter(autor__nome_autor__icontains=query)
                print(object_list.query)
            elif select_atribute == 'editora':
                object_list = self.model.objects.filter(editora__nome_editora__icontains=query)
                print(object_list.query)
            elif select_atribute == 'genero':
                object_list = self.model.objects.filter(genero__genero__icontains=query)
                print(object_list.query)
            else:
                object_list = self.model.objects.none()
        else:
            object_list = self.model.objects.none()
        return object_list

livros/templates/livros/livro_base.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<div class="container">
  <div class="row">
    {% block prelivro %}{% endblock %}
    {% block livro_conteudo %}{% endblock %}
    {% block apos_livro %}{% endblock %}
  </div>
</div>

{% endblock %}

livros/templates/livros/livro_detail.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'livros/css/pagina-livro.css'%}">
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{livro.titulo}}</title>
  </head>
  <div id="menu-outer">
      <div class="table">
        <ul id="horizontal-list">
          <li><a href="{% url 'home' %}">LivrosSocial</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'livros:all' %}">Livros</a></li>
            <li><a href="{% url 'livros:create' %}">Cadastrar Livros</a></li>
            <li style='color:white;'><a href="{% url 'accounts:profile' pk=user.profile.pk %}" style='color:white !important;'>Perfil</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'accounts:login' %}">Login</a></li>
          <li><a href="{% url 'accounts:signup' %}">Cadastre-se</a></li>
       {% endif %}
        </ul>
      </div>
  </div>
  <body>
    <div>
      {% if livro.capa %}
        <img src="{{ livro.capa.url }}" alt="{{ livro.titulo }}" class = 'capa-livro'>
      {% else %}
      {% endif %}
    </div>
    <div>
      <h1 class="titulo-livro">{{livro.titulo}}
        {% if user in livro.leitores.all %}
          <a href="{% url 'livros:leave' pk=livro.pk %}" class="btn btn-lg btn-warning" style='font-size:20px;'><span class="fa fa-times-circle-o"></span>Retira</a>
        {% else %}
          <a href="{% url 'livros:join' pk=livro.pk %}" class="btn btn-lg btn-warning" style='font-size:20px;'><span class="fa fa-check-circle-o"></span>Coloca</a>
        {% endif %}</h1>
    </div>
    <div class = 'estrelas'>

        <div class="rate">
            <input type="radio" id="star5" name="rate" value="5" />
            <label for="star5" title="text">5 stars</label>
            <input type="radio" id="star4" name="rate" value="4" />
            <label for="star4" title="text">4 stars</label>
            <input type="radio" id="star3" name="rate" value="3" />
            <label for="star3" title="text">3 stars</label>
            <input type="radio" id="star2" name="rate" value="2" />
            <label for="star2" title="text">2 stars</label>
            <input type="radio" id="star1" name="rate" value="1" />
            <label for="star1" title="text">1 star</label>
          </div>
    </div>
    <div class = 'conteudo-livro'>
        <p><span>Autor: </span>{{ livro.autor.nome_autor }}</p>
        <p><span>Status:</span>
          {% if user in livro.leitores.all %}
           Já está na sua lista
          {% else %}
            Não está contido na sua lista
          {% endif %}
        </p>
        <p><span>ISBN: </span>{{ livro.pk }}</p>
        <p><span>Nota média: </span>{{ livro.nota_media }}</p>
        <p><span>Número de avaliações: </span>{{ livro.total_de_notas }}</p>
        <p><span>Data de publicação: </span>{{ livro.data_publicacao }}</p>
        <p><span>Editora: </span>{{livro.editora.nome_editora}}</p>
        <p><span>Número de páginas: </span>{{ livro.num_paginas }}</p>
    </div>
    <div class = 'comentarios'>
        <div class="container">
        {% if user.is_authenticated %}
          <a class="btn btn-primary btn-comment" href="{% url 'resenhas:adiciona_resenha' pk=livro.pk %}" style='color:black;'>Adicionar Resenha</a>
        {% endif %}
        <h1 class = 'titulo-comentarios'>Comentários</h1>
        <div class = 'espaço-comentários'><div id = 'texto-comentario'>
          {% for resenha in livro.resenhas.all %}
          <br>
              {% if resenha.resenha_aprovada or user.is_superuser %}

                      {{ resenha.data_publicacao }}
                      {% if not resenha.resenha_aprovada %}
                          <a class="btn btn-primary" href="{% url 'resenhas:remove_resenha' pk=resenha.pk %}"><span class="fa fa-remove"></span></a>
                          <a class="btn btn-primary" href="{% url 'resenhas:aprova_resenha' pk=resenha.pk %}"><span class="fa fa-check"></span></a>
                      {% endif %}

                  <p>{{ resenha.texto|safe|linebreaks }}</p>
                  <p>Publicada por: <strong>{{ resenha.usuario }}</strong></p>

              {% endif %}
          {% empty %}
              <p>Nenhuma resenha publicada.</p>
          {% endfor %}
        </div></div>
    </div>
  </body>
</html>

livros/templates/livros/livro_form.html
{% extends "livros/livro_base.html" %}
{% load bootstrap4 %}

{% block livro_conteudo %}
<div class="container">
  <h4 class='form-group'>Crie um novo livro</h4>
  <form method="POST" action="{% url 'livros:create' %}" id="livroForm" enctype="multipart/form-data">
  	{% csrf_token %}
  	{% bootstrap_form form %}
    {% buttons %}
  		<button type="submit" class="btn btn-primary btn-large">Criar</button>
  	{% endbuttons %}
  </form>
</div>
{% endblock %}

livros/templates/livros/livro_list.html
{% extends "livros/livro_base.html" %}

{% block prelivro %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2 style='color:white;'>
			Bem Vindo de Volta
			<br>@{{user.username }}
		</h2>

    {% endif %}
			<h2 style='color:white;'>Livros</h2>

			<p style='color:white;'>Bem vindo a pagina de Livros! <br>Selecione um livro que você possui interessante</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'livros:create' %}" class="btn btn-warning" role="button"><span class="fa fa-plus"></span> Crie um novo Livro</a>
	{% endif %}
</div>
{% endblock %}

{% block livro_conteudo %}
<div class="col-md-8">
	<div class="list-livro">
		{% for livro in object_list %}
		<a href="{% url 'livros:single' pk=livro.pk %}"
		class="list-livro-item list-livro-item-action flex-column align-items-start">
			<h3 class="mb-1" style='color:#F4BD38;'>{{ livro.titulo }}</h3>
			<p class="mb-1"style='color:#F4BD38;'>{{ livro.num_paginas }}</p>
			<div class="d-flex w-40 justify-content-between">
				<small class="text-muted"><span class="badge badge-secondary">
					{{ livro.leitores.count }}</span> leitor{{ livro.leitores.count|pluralize:"es" }}</small>
			<span></span><span></span>
			</div>
		</a>

		{% endfor %}
	</div>
</div>
{% endblock %}